baseURL = "https://asalocin.github.io/"
languageCode = "es"
title = "Asalocin"
theme = "book"
publishDir = "docs"

[params]
  # opciones específicas del tema
  BookSection = "docs"  # sección que se convertirá en menú principal :contentReference[oaicite:1]{index=1}



[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
